---
title: "Counterfactual_conditionals"
author: "Nicholas Lester"
date: "5/22/2020"
output:
  github_document:
  pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, warning=F, message = F, error = F)
```

##############################
# Revised analysis for 
# counterfactual conditionals
# -- restricted sample
# -- full sample
# -- random forests
# -- CART
# -- DCA
##############################

```{r clear_memory, include = F}
rm(list=ls(all=T))
```

###########
# Libraries
###########
```{r load_libraries, include = F}
library(caret)
library(randomForest)
library(e1071)
library(pdp)
library(partykit)
library(ggplot2)
```

#########################
# Load and clean the data
#########################
```{r load_and_process_data}
# Full sample
dat.full = read.table("./counterfactuals_revised.txt", quote="", comment.char="", sep="\t", header=T)

summary(dat.full)

## Fix weird levels
dat.full$Symmetry[dat.full$Symmetry=="Symmetric "] = "Symmetric"

dat.full$Macroarea[dat.full$Macroarea=="South-America"] = "South_America"


## Reorder factor levels
dat.full$TAM_apodosis = factor(dat.full$TAM_apodosis, levels(dat.full$TAM_apodosis)[c(4, 1:3)])
dat.full$TAM_protasis = factor(dat.full$TAM_protasis, levels(dat.full$TAM_protasis)[c(5, 1:4)])

## Remove items that have two few observations
dat.full = dat.full[dat.full$Symmetry %in% c("Asymmetric", 
                                             "Symmetric") & 
                    !dat.full$Clause_Linking_Device %in% c("Coordinating_conjunction", 
                                                           "Sequential_device", 
                                                           "Unknown") &
                    dat.full$TAM_protasis != "Nominalized_clause" &
                    dat.full$TAM_apodosis != "Unmarked",]
dat.full = droplevels(dat.full)

summary(dat.full)

# Restricted sample
dat.restr = read.table("./restricted_sample.txt", quote="", comment.char="", sep="\t", header=T)[,-c(7:9)]

summary(dat.restr)

## Change the colnames to conform to original table
colnames(dat.restr) = colnames(dat.full)[-7]

## Fix weird levels
dat.restr$Symmetry[dat.restr$Symmetry=="Symmetric "] = "Symmetric"

dat.restr$Clause_Linking_Device[dat.restr$Clause_Linking_Device=="Non-specialized device"] = "Non-specialized"

dat.restr$Macroarea = as.factor(ifelse(dat.restr$Macroarea=="South-America", "South_America", as.vector(dat.restr$Macroarea)))

dat.restr = droplevels(dat.restr[!dat.restr$Symmetry %in% c("No TAM values", "Symmetric/Asymmetric"),])

summary(dat.restr)

## Reorder factor levels
dat.restr$TAM_apodosis = factor(dat.restr$TAM_apodosis, levels(dat.restr$TAM_apodosis)[c(4, 1:3)])
dat.restr$TAM_protasis = factor(dat.restr$TAM_protasis, levels(dat.restr$TAM_protasis)[c(5, 1:4)])

## Remove items that have two few observations
dat.restr = dat.restr[!dat.restr$Clause_Linking_Device %in% c("Unknown") &
                        dat.restr$TAM_protasis != "Nominalized clause" &
                        dat.restr$TAM_apodosis != "Unmarked",]
dat.restr = droplevels(dat.restr)

summary(dat.restr)
```

###################################
# Modeling with CART-style analysis
###################################
```{r cart_analysis}
## Restricted sample
ct.restr = ctree(Symmetry ~ Clause_Linking_Device + TAM_protasis + TAM_apodosis + Macroarea, data=dat.restr)

plot(ct.restr, gp = gpar(fontsize=8))

### Classification accuracy
t = table(predict(ct.restr), dat.restr$Symmetry)
d = sum(diag(t))
s = sum(t)
ca = d/s

### baseline
t2 = table(dat.restr$Symmetry)
bl = max(t2)/sum(t2)
ca-bl

### lax baseline
t3 = prop.table(t2)
bl2 = t3[1]^2 + t3[2]^2
ca-bl2

## Full sample
ct.full = ctree(Symmetry ~ Clause_Linking_Device + TAM_protasis + TAM_apodosis + Macroarea, data=dat.full)

plot(ct.full, gp = gpar(fontsize=8))

### Classification accuracy
t = table(predict(ct.full), dat.full$Symmetry)
d = sum(diag(t))
s = sum(t)
ca = d/s

### baseline
t2 = table(dat.full$Symmetry)
bl = max(t2)/sum(t2)
ca-bl

### lax baseline
t3 = prop.table(t2)
bl2 = t3[1]^2 + t3[2]^2
ca-bl2
```

###########################################
# Modeling with random forests: Full sample
###########################################
```{r random_forest}
set.seed(1986)

# Training control parameters
trControl <- trainControl(method = "cv",
                          number = 10,
                          search = "grid")

# Model, first attempt
model = train(Symmetry ~ Clause_Linking_Device + 
                         TAM_protasis + 
                         TAM_apodosis + 
                         Macroarea + 
                         Real_vs_Counterfactual_Linking, 
              data = dat.full, 
              method = "rf", 
              trControl = trControl,
              metric = "Accuracy")

model # 82% accuracy

# Model tuning
## mtry
set.seed(1986)

tuneGrid = expand.grid(.mtry = c(1:10))

model_mtry = train(Symmetry ~ Clause_Linking_Device + 
                              TAM_protasis + 
                              TAM_apodosis + 
                              Macroarea + 
                              Real_vs_Counterfactual_Linking, 
                 data = dat.full,
                 method = "rf",
                 metric = "Accuracy",
                 tuneGrid = tuneGrid,
                 trControl = trControl,
                 importance = TRUE,
                 nodesize = 14,
                 ntree = 300)

best.mtry = model_mtry$bestTune$mtry # mtry=9

max(model_mtry$results$Accuracy) # up to 83% with mtry=9

## max nodes
store_maxnode = list()
tuneGrid = expand.grid(.mtry = best.mtry)
for (maxnodes in c(5:15)) {
  set.seed(1986)
  model_maxnode = train(Symmetry ~ Clause_Linking_Device + 
                                   TAM_protasis + 
                                   TAM_apodosis + 
                                   Macroarea + 
                                   Real_vs_Counterfactual_Linking,
                      data = dat.full,
                      method = "rf",
                      metric = "Accuracy",
                      tuneGrid = tuneGrid,
                      trControl = trControl,
                      importance = TRUE,
                      nodesize = 14,
                      maxnodes = maxnodes,
                      ntree = 300)
  current_iteration = toString(maxnodes)
  store_maxnode[[current_iteration]] = model_maxnode
}

results.mtry = resamples(store_maxnode)
summary(results.mtry) # max nodes = 9

best.maxnodes = 9

# Best number of trees
store_maxtrees = list()
for (ntree in c(250, 300, 350, 400, 450, 500, 550, 600, 800, 1000, 2000)) {
  set.seed(1986)
  model_maxtrees = train(Symmetry ~ Clause_Linking_Device + 
                                    TAM_protasis + 
                                    TAM_apodosis + 
                                    Macroarea,
                       data = dat.full,
                       method = "rf",
                       metric = "Accuracy",
                       tuneGrid = tuneGrid,
                       trControl = trControl,
                       importance = TRUE,
                       nodesize = 14,
                       maxnodes = 9,
                       ntree = ntree)
  key = toString(ntree)
  store_maxtrees[[key]] = model_maxtrees
}

results_tree = resamples(store_maxtrees)
summary(results_tree) # not much difference, but 300 should work

best.ntree = 300

# Final model
set.seed(1986)
model = randomForest(Symmetry ~ Clause_Linking_Device + 
                                TAM_protasis + 
                                TAM_apodosis + 
                                Macroarea,
              data = dat.full, 
              method = "rf", 
              trControl = trControl,
              metric = "Accuracy",
              tuneGrid = tuneGrid,
              ntree = best.ntree,
              maxnodes = best.maxnodes,
              importance = T,
              nodesize = 14)

print(model)

# Check the partial probabilities 
pred.prob <- function(object, newdata) {  # see ?predict.svm
  pred <- predict(object, newdata, type = "prob")
  prob.sym <- pred[, "Symmetric"]
  mean(prob.sym)
}

p.full = partial(model, pred.var=c("TAM_protasis", "TAM_apodosis"), pred.fun = pred.prob, plot=T, plot.engine = "ggplot2")

p.full + xlab("TAM of protasis") +
          ggtitle("TAM of apodosis") +
          ylab("Probability of asymmetry") +
          theme_bw() + 
          theme(plot.title = element_text(hjust = 0.5), 
                axis.text.x = element_text(angle = 45, hjust = 1))


#################################################
# Modeling with random forests: Restricted sample
#################################################

set.seed(1986)

# Training control parameters
trControl <- trainControl(method = "cv",
                          number = 10,
                          search = "grid")

# Model, first attempt
model = train(Symmetry ~ Clause_Linking_Device + 
                TAM_protasis + 
                TAM_apodosis + 
                Macroarea, 
              data = dat.restr, 
              method = "rf", 
              trControl = trControl,
              metric = "Accuracy")

model # 83% accuracy

# Model tuning
## mtry
set.seed(1986)

tuneGrid = expand.grid(.mtry = c(1:10))

model_mtry = train(Symmetry ~ Clause_Linking_Device + 
                     TAM_protasis + 
                     TAM_apodosis + 
                     Macroarea, 
                   data = dat.restr,
                   method = "rf",
                   metric = "Accuracy",
                   tuneGrid = tuneGrid,
                   trControl = trControl,
                   importance = TRUE,
                   nodesize = 14,
                   ntree = 300)

best.mtry = model_mtry$bestTune$mtry # mtry=7

max(model_mtry$results$Accuracy) # up to 83% with mtry=7

## max nodes
store_maxnode = list()
tuneGrid = expand.grid(.mtry = best.mtry)
for (maxnodes in c(5:15)) {
  set.seed(1986)
  model_maxnode = train(Symmetry ~ Clause_Linking_Device + 
                          TAM_protasis + 
                          TAM_apodosis + 
                          Macroarea,
                        data = dat.restr,
                        method = "rf",
                        metric = "Accuracy",
                        tuneGrid = tuneGrid,
                        trControl = trControl,
                        importance = TRUE,
                        nodesize = 14,
                        maxnodes = maxnodes,
                        ntree = 300)
  current_iteration = toString(maxnodes)
  store_maxnode[[current_iteration]] = model_maxnode
}

results_mtry = resamples(store_maxnode)
summary(results_mtry) # max nodes = 6

best.maxnodes = 6

# Best number of trees
store_maxtrees = list()
for (ntree in c(250, 300, 350, 400, 450, 500, 550, 600, 800, 1000, 2000)) {
  set.seed(1986)
  model_maxtrees = train(Symmetry ~ Clause_Linking_Device + 
                           TAM_protasis + 
                           TAM_apodosis + 
                           Macroarea,
                         data = dat.restr,
                         method = "rf",
                         metric = "Accuracy",
                         tuneGrid = tuneGrid,
                         trControl = trControl,
                         importance = TRUE,
                         nodesize = 14,
                         maxnodes = 11,
                         ntree = ntree)
  key = toString(ntree)
  store_maxtrees[[key]] = model_maxtrees
}

results_tree <- resamples(store_maxtrees)
summary(results_tree) # 250

best.ntree = 250

# Final model
set.seed(1986)
model = randomForest(Symmetry ~ Clause_Linking_Device + 
                       TAM_protasis + 
                       TAM_apodosis + 
                       Macroarea, 
                     data = dat.restr, 
                     method = "rf", 
                     trControl = trControl,
                     metric = "Accuracy",
                     tuneGrid = tuneGrid,
                     ntree = best.ntree,
                     maxnodes = best.maxnodes,
                     importance = T,
                     nodesize = 14)

print(model)

# Check the partial probabilities 
pred.prob <- function(object, newdata) {  # see ?predict.svm
  pred <- predict(object, newdata, type = "prob")
  prob.sym <- pred[, "Symmetric"]
  mean(prob.sym)
}

p.restr = partial(model, pred.var=c("TAM_protasis", "TAM_apodosis"), pred.fun = pred.prob, plot=T, plot.engine="ggplot2")

p.restr + xlab("TAM of protasis") +
          ggtitle("TAM of apodosis") +
          ylab("Probability of asymmetry") +
          theme_bw() + 
          theme(plot.title = element_text(hjust = 0.5), 
                axis.text.x = element_text(angle = 45, hjust = 1))
```

######################################
# Distinctive collexeme analysis (GUI)
######################################
```{r GUI_to_run_DCA}
# source("http://www.linguistics.ucsb.edu/faculty/stgries/teaching/groningen/coll.analysis.r")
```
